# Generated by Django 5.0.7 on 2024-09-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehistory',
            name='image_path',
        ),
        migrations.AddField(
            model_name='imagehistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
