# Generated by Django 5.0.7 on 2024-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_imagehistory_image_path_imagehistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehistory',
            name='prompt',
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='image',
            field=models.ImageField(default='/static/images/placeholder.jpg', upload_to='images/'),
        ),
    ]
