# Generated by Django 5.0.7 on 2024-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_imagehistory_prompt_alter_imagehistory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehistory',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
